import type { CalculatorId } from "@/lib/calculators";

/**
 * Calculators that expose a [VIZ] tab in the tool workspace.
 * Keep this free of React component imports so header tab presence
 * never depends on schematic module evaluation.
 */
const VIZ_CALCULATOR_IDS = [
  "critical-load-analysis",
  "ups-runtime",
  "ebike-range-estimator",
  "ebike-charging-cost",
  "ebike-max-speed",
  "ebike-charge-time",
  "battery-percentage",
  "battery-runtime",
  "battery-charging-time",
  "battery-energy",
  "battery-bank-size",
  "inverter-sizing",
  "dc-cable-size",
  "watts-to-amps",
  "amps-to-watts",
  "residential-voltage-drop",
  "ohms-law",
  "solar-panel-size",
  "solar-battery-bank",
  "solar-charge-controller-size",
  "solar-daily-yield",
  "ev-charging-cost",
  "ev-charge-time",
  "ev-cost-per-mile",
  "ev-battery-range",
  "ev-level1-vs-level2",
  "ev-vs-ice-maintenance",
  "ev-fast-charging-time",
  "ev-charging-temperature-impact",
  "ev-truck-range",
  "ev-fleet-tco",
  "ev-bus-battery",
  "ev-forklift-runtime",
  "ev-delivery-van-efficiency",
  "escooter-range",
  "escooter-tire-pressure",
  "escooter-max-speed",
  "escooter-hill-climb",
  "rv-solar-calculator",
  "marine-battery-bank",
  "portable-power-station-recharge",
  "12v-to-120v-inverter",
  "camping-fridge-runtime",
  "appliance-daily-cost",
  "appliance-monthly-energy",
  "energy-consumption",
  "heater-cost",
  "pool-energy-thermal-cover",
  "heat-loss-insulation",
  "home-insulation-savings",
  "led-savings-roi",
  "led-vs-incandescent-roi",
  "tou-shifting-savings",
  "demand-charge-calculator",
  "v2g-financial-return",
  "battery-arbitrage-roi",
  "battery-cost",
  "electricity-bill",
  "ah-to-wh",
  "wh-to-ah",
  "kva-to-kw",
  "conductor-resistance-temperature",
  "battery-depth-of-discharge",
  "battery-efficiency",
  "battery-series-parallel",
  "battery-c-rate",
  "volts-to-watts",
  "watts-to-volts",
  "power-factor",
  "ac-inrush-current",
] as const satisfies readonly CalculatorId[];

export const CALCULATOR_VIZ_IDS = new Set<string>(VIZ_CALCULATOR_IDS);

export function hasCalculatorViz(id: CalculatorId): boolean {
  return (VIZ_CALCULATOR_IDS as readonly string[]).includes(id);
}
