import type { PdfReportData } from "@/lib/pdf-utils";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 50;
const LINE_HEIGHT = 16;
const BODY_SIZE = 11;
const TITLE_SIZE = 18;
const SECTION_SIZE = 13;

function escapePdfText(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildContentStream(lines: Array<{ text: string; size: number }>): string {
  let y = PAGE_HEIGHT - MARGIN;
  const commands: string[] = ["BT"];

  for (const line of lines) {
    if (line.text === "") {
      y -= LINE_HEIGHT;
      continue;
    }

    commands.push(
      `/F1 ${line.size} Tf`,
      `${MARGIN} ${y} Td`,
      `(${escapePdfText(line.text)}) Tj`,
      `${-LINE_HEIGHT} 0 Td`
    );
    y -= LINE_HEIGHT;
  }

  commands.push("ET");
  return commands.join("\n");
}

function recordLines(
  title: string,
  record: Record<string, string | number>
): Array<{ text: string; size: number }> {
  const lines: Array<{ text: string; size: number }> = [
    { text: title, size: SECTION_SIZE },
  ];

  for (const [label, value] of Object.entries(record)) {
    lines.push({ text: `${label}: ${String(value)}`, size: BODY_SIZE });
  }

  return lines;
}

/** Build a minimal PDF report (browser + edge, no external deps). */
export function buildReportPdf(data: PdfReportData): Uint8Array {
  const lines: Array<{ text: string; size: number }> = [
    { text: data.calculatorName || "WattQuick Calculator", size: TITLE_SIZE },
    { text: "", size: BODY_SIZE },
    ...recordLines("Inputs", data.inputs),
    { text: "", size: BODY_SIZE },
    ...recordLines("Results", data.results),
    { text: "", size: BODY_SIZE },
    { text: "Generated by WattQuick", size: BODY_SIZE },
  ];

  const content = buildContentStream(lines);
  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    `3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n`,
    `4 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`,
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];

  for (const object of objects) {
    offsets.push(pdf.length);
    pdf += object;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";

  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new TextEncoder().encode(pdf);
}

export function isValidPdfReportData(body: unknown): body is PdfReportData {
  if (!body || typeof body !== "object") return false;

  const candidate = body as Partial<PdfReportData>;
  return (
    typeof candidate.calculatorName === "string" &&
    candidate.inputs !== null &&
    typeof candidate.inputs === "object" &&
    !Array.isArray(candidate.inputs) &&
    candidate.results !== null &&
    typeof candidate.results === "object" &&
    !Array.isArray(candidate.results)
  );
}
