export type {
  CalculatorCategory,
  CalculatorComputeFn,
  CalculatorDefinition,
  CalculatorFieldDef,
  CalculatorFieldInputType,
  CalculatorFieldOption,
  CalculatorId,
  CalculatorMeta,
  CalculatorResultConfig,
  CalculatorResultDisplay,
  CalculatorSeoContent,
  CalculatorSeoSection,
  CalculatorContentSection,
} from "./types";
export {
  calculators,
  CALCULATOR_SLUGS,
  type CalculatorSlug,
} from "@/data/calculators";
export {
  CALCULATOR_CATEGORY_DESCRIPTIONS,
  CALCULATOR_CATEGORY_LABELS,
  toMeta,
} from "./types";
export {
  CALCULATOR_ORDER,
  getAllCalculatorDefinitions,
  getAllCalculatorMeta,
  getCalculatorDefinition,
  getCalculatorMeta,
  getCalculatorsByCategory,
  getSuggestions,
} from "./registry";
export { getRelatedCalculators } from "./related";
export { isCalculatorId } from "./utils";
export { isCalculatorCategory } from "./categories";
export {
  CALCULATOR_ID_TO_GUIDE_SLUG,
  CALCULATOR_TOOL_SLUGS,
  GUIDE_LANDING_SLUGS,
  TOOLS_CALCULATORS_SLUGS,
  getAllGuideLandings,
  getCalculatorIdForToolSlug,
  getGuideLanding,
  getGuideLinkLabelForCalculator,
  getGuidePathForCalculator,
  getGuideLandingsByCategory,
  isCalculatorToolSlug,
  isGuideLandingSlug,
  isToolsCalculatorsSlug,
  type CalculatorToolSlug,
  type GuideLandingSlug,
  type ToolsCalculatorsSlug,
} from "./calculator-landings-registry";
export type {
  GuideLandingContent,
  GuideLandingDefinition,
  GuideLandingFooterResource,
  GuideLandingFaq,
} from "./landing-types";
export {
  getCalculatorToolHref,
  getGuideLandingHref,
  getResourceGuideHref,
} from "./landing-types";
export {
  BATTERY_PERCENTAGE_FOOTER_RESOURCES,
  BATTERY_PERCENTAGE_GUIDE_HREF,
  BATTERY_PERCENTAGE_LANDING_SLUG,
  BATTERY_PERCENTAGE_LANDING_SLUGS,
  BATTERY_PERCENTAGE_TOOL_HREF,
  getAllBatteryPercentageLandings,
  getBatteryPercentageLanding,
  isBatteryPercentageLandingSlug,
  type BatteryPercentageGuideDefinition,
  type BatteryPercentageLandingSlug,
} from "./batterypercentageLandings";
export {
  EV_SOC_FOOTER_RESOURCES,
  EV_SOC_GUIDE_HREF,
  EV_SOC_LANDING_SLUG,
  EV_SOC_LANDING_SLUGS,
  getAllEvSocLandings,
  getEvSocLanding,
  isEvSocLandingSlug,
  type EvSocGuideDefinition,
  type EvSocLandingSlug,
} from "./evSocLandings";
export {
  REMAINING_BATTERY_CAPACITY_GUIDE_HREF,
  REMAINING_BATTERY_CAPACITY_LANDING_SLUG,
  REMAINING_BATTERY_CAPACITY_LANDING_SLUGS,
  getAllRemainingBatteryCapacityLandings,
  getRemainingBatteryCapacityLanding,
  isRemainingBatteryCapacityLandingSlug,
  type RemainingBatteryCapacityGuideDefinition,
  type RemainingBatteryCapacityLandingSlug,
} from "./remainingBatteryCapacityLandings";
export {
  ELECTRIC_SCOOTER_RANGE_CALCULATOR_GUIDE_HREF,
  ELECTRIC_SCOOTER_RANGE_CALCULATOR_LANDING_SLUG,
  HOW_FAR_CAN_MY_ESCOOTER_GO_GUIDE_HREF,
  HOW_FAR_CAN_MY_ESCOOTER_GO_LANDING_SLUG,
  ESCOOTER_BATTERY_RANGE_ESTIMATOR_GUIDE_HREF,
  ESCOOTER_BATTERY_RANGE_ESTIMATOR_LANDING_SLUG,
  ESCOOTER_RANGE_CALCULATOR_ID,
  ESCOOTER_RANGE_FOOTER_RESOURCES,
  ESCOOTER_RANGE_LANDING_SLUGS,
  ESCOOTER_RANGE_TOOL_HREF,
  ESCOOTER_RANGE_TOOL_PATH,
  getAllEscooterRangeLandings,
  getEscooterRangeLanding,
  getEscooterRangeToolFooterLinks,
  isEscooterRangeLandingSlug,
  type EscooterRangeGuideDefinition,
  type EscooterRangeLandingSlug,
} from "./escooterRangeLandings";
export {
  ELECTRIC_TRUCK_RANGE_AND_PAYLOAD_CALCULATOR_GUIDE_HREF,
  ELECTRIC_TRUCK_RANGE_AND_PAYLOAD_CALCULATOR_LANDING_SLUG,
  IMPACT_OF_PAYLOAD_ON_EV_TRUCK_RANGE_GUIDE_HREF,
  IMPACT_OF_PAYLOAD_ON_EV_TRUCK_RANGE_LANDING_SLUG,
  EV_HEAVY_DUTY_TRUCK_EFFICIENCY_CALCULATOR_GUIDE_HREF,
  EV_HEAVY_DUTY_TRUCK_EFFICIENCY_CALCULATOR_LANDING_SLUG,
  EV_TRUCK_RANGE_CALCULATOR_ID,
  EV_TRUCK_RANGE_FOOTER_RESOURCES,
  EV_TRUCK_RANGE_LANDING_SLUGS,
  EV_TRUCK_RANGE_TOOL_HREF,
  EV_TRUCK_RANGE_TOOL_PATH,
  getAllEvTruckRangeLandings,
  getEvTruckRangeLanding,
  getEvTruckRangeToolFooterLinks,
  isEvTruckRangeLandingSlug,
  type EvTruckRangeGuideDefinition,
  type EvTruckRangeLandingSlug,
} from "./evTruckRangeLandings";
export {
  UPS_RUNTIME_CALCULATOR_GUIDE_HREF,
  UPS_RUNTIME_CALCULATOR_LANDING_SLUG,
  BATTERY_BACKUP_TIME_ESTIMATOR_GUIDE_HREF,
  BATTERY_BACKUP_TIME_ESTIMATOR_LANDING_SLUG,
  ESTIMATE_UPS_BATTERY_CAPACITY_BASED_ON_LOAD_GUIDE_HREF,
  ESTIMATE_UPS_BATTERY_CAPACITY_BASED_ON_LOAD_LANDING_SLUG,
  UPS_RUNTIME_CALCULATOR_ID,
  UPS_RUNTIME_FOOTER_RESOURCES,
  UPS_RUNTIME_LANDING_SLUGS,
  UPS_RUNTIME_TOOL_HREF,
  UPS_RUNTIME_TOOL_PATH,
  getAllUpsRuntimeLandings,
  getUpsRuntimeLanding,
  getUpsRuntimeToolFooterLinks,
  isUpsRuntimeLandingSlug,
  type UpsRuntimeGuideDefinition,
  type UpsRuntimeLandingSlug,
} from "./upsRuntimeLandings";
export {
  BATTERY_BANK_SIZE_CALCULATOR_GUIDE_HREF,
  BATTERY_BANK_SIZE_CALCULATOR_LANDING_SLUG,
  AMP_HOURS_NEEDED_FOR_BATTERY_BANK_GUIDE_HREF,
  AMP_HOURS_NEEDED_FOR_BATTERY_BANK_LANDING_SLUG,
  OFF_GRID_BATTERY_CAPACITY_ESTIMATOR_GUIDE_HREF,
  OFF_GRID_BATTERY_CAPACITY_ESTIMATOR_LANDING_SLUG,
  BATTERY_BANK_SIZE_CALCULATOR_ID,
  BATTERY_BANK_SIZE_FOOTER_RESOURCES,
  BATTERY_BANK_SIZE_LANDING_SLUGS,
  BATTERY_BANK_SIZE_TOOL_HREF,
  BATTERY_BANK_SIZE_TOOL_PATH,
  getAllBatteryBankSizeLandings,
  getBatteryBankSizeLanding,
  getBatteryBankSizeToolFooterLinks,
  isBatteryBankSizeLandingSlug,
  type BatteryBankSizeGuideDefinition,
  type BatteryBankSizeLandingSlug,
} from "./batteryBankSizeLandings";
export {
  CALCULATE_E_BIKE_DISTANCE_PER_CHARGE_GUIDE_HREF,
  CALCULATE_E_BIKE_DISTANCE_PER_CHARGE_LANDING_SLUG,
  ELECTRIC_BIKE_BATTERY_RANGE_CALCULATOR_GUIDE_HREF,
  ELECTRIC_BIKE_BATTERY_RANGE_CALCULATOR_LANDING_SLUG,
  EBIKE_RANGE_ESTIMATOR_GUIDE_HREF,
  EBIKE_RANGE_ESTIMATOR_LANDING_SLUG,
  EBIKE_RANGE_ESTIMATOR_CALCULATOR_ID,
  EBIKE_RANGE_ESTIMATOR_FOOTER_RESOURCES,
  EBIKE_RANGE_ESTIMATOR_LANDING_SLUGS,
  EBIKE_RANGE_ESTIMATOR_TOOL_HREF,
  EBIKE_RANGE_ESTIMATOR_TOOL_PATH,
  getAllEbikeRangeEstimatorLandings,
  getEbikeRangeEstimatorLanding,
  getEbikeRangeEstimatorToolFooterLinks,
  isEbikeRangeEstimatorLandingSlug,
  type EbikeRangeEstimatorGuideDefinition,
  type EbikeRangeEstimatorLandingSlug,
} from "./ebikeRangeLandings";
export {
  CALCULATE_SOLAR_PANEL_AND_BATTERY_CAPACITY_FOR_OFF_GRID_LOADS_GUIDE_HREF,
  CALCULATE_SOLAR_PANEL_AND_BATTERY_CAPACITY_FOR_OFF_GRID_LOADS_LANDING_SLUG,
  OFF_GRID_SOLAR_SYSTEM_SIZING_CALCULATOR_GUIDE_HREF,
  OFF_GRID_SOLAR_SYSTEM_SIZING_CALCULATOR_LANDING_SLUG,
  TWELVE_V_TWENTY_FOUR_V_SOLAR_POWER_SYSTEM_ESTIMATOR_GUIDE_HREF,
  TWELVE_V_TWENTY_FOUR_V_SOLAR_POWER_SYSTEM_ESTIMATOR_LANDING_SLUG,
  RV_SOLAR_CALCULATOR_CALCULATOR_ID,
  RV_SOLAR_CALCULATOR_FOOTER_RESOURCES,
  RV_SOLAR_CALCULATOR_LANDING_SLUGS,
  RV_SOLAR_CALCULATOR_TOOL_HREF,
  RV_SOLAR_CALCULATOR_TOOL_PATH,
  getAllRvSolarCalculatorLandings,
  getRvSolarCalculatorLanding,
  getRvSolarCalculatorToolFooterLinks,
  isRvSolarCalculatorLandingSlug,
  type RvSolarCalculatorGuideDefinition,
  type RvSolarCalculatorLandingSlug,
} from "./rvSolarCalculatorLandings";
export {
  APPLIANCE_MONTHLY_ENERGY_CALCULATOR_ID,
  APPLIANCE_MONTHLY_ENERGY_CONSUMPTION_CALCULATOR_GUIDE_HREF,
  APPLIANCE_MONTHLY_ENERGY_CONSUMPTION_CALCULATOR_LANDING_SLUG,
  CALCULATE_ELECTRICITY_COST_PER_APPLIANCE_GUIDE_HREF,
  CALCULATE_ELECTRICITY_COST_PER_APPLIANCE_LANDING_SLUG,
  CONVERT_APPLIANCE_WATTS_TO_MONTHLY_KWH_GUIDE_HREF,
  CONVERT_APPLIANCE_WATTS_TO_MONTHLY_KWH_LANDING_SLUG,
  APPLIANCE_MONTHLY_ENERGY_FOOTER_RESOURCES,
  APPLIANCE_MONTHLY_ENERGY_LANDING_SLUGS,
  APPLIANCE_MONTHLY_ENERGY_TOOL_HREF,
  APPLIANCE_MONTHLY_ENERGY_TOOL_PATH,
  getAllApplianceMonthlyEnergyLandings,
  getApplianceMonthlyEnergyLanding,
  getApplianceMonthlyEnergyToolFooterLinks,
  isApplianceMonthlyEnergyLandingSlug,
  type ApplianceMonthlyEnergyGuideDefinition,
  type ApplianceMonthlyEnergyLandingSlug,
} from "./applianceMonthlyEnergyLandings";
export {
  BUILDING_ENVELOPE_HEAT_LOSS_CALCULATOR_GUIDE_HREF,
  BUILDING_ENVELOPE_HEAT_LOSS_CALCULATOR_LANDING_SLUG,
  ESTIMATE_HEAT_LOSS_BY_R_VALUE_GUIDE_HREF,
  ESTIMATE_HEAT_LOSS_BY_R_VALUE_LANDING_SLUG,
  HEAT_LOSS_CALCULATION_CALCULATOR_GUIDE_HREF,
  HEAT_LOSS_CALCULATION_CALCULATOR_LANDING_SLUG,
  HEAT_LOSS_INSULATION_CALCULATOR_ID,
  HEAT_LOSS_INSULATION_FOOTER_RESOURCES,
  HEAT_LOSS_INSULATION_LANDING_SLUGS,
  HEAT_LOSS_INSULATION_TOOL_HREF,
  HEAT_LOSS_INSULATION_TOOL_PATH,
  getAllHeatLossInsulationLandings,
  getHeatLossInsulationLanding,
  getHeatLossInsulationToolFooterLinks,
  isHeatLossInsulationLandingSlug,
  type HeatLossInsulationGuideDefinition,
  type HeatLossInsulationLandingSlug,
} from "./heatLossInsulationLandings";
export {
  ENERGY_SAVINGS_FROM_WALL_AND_WINDOW_INSULATION_GUIDE_HREF,
  ENERGY_SAVINGS_FROM_WALL_AND_WINDOW_INSULATION_LANDING_SLUG,
  ESTIMATE_ANNUAL_HEATING_AND_COOLING_SAVINGS_GUIDE_HREF,
  ESTIMATE_ANNUAL_HEATING_AND_COOLING_SAVINGS_LANDING_SLUG,
  HOME_INSULATION_SAVINGS_CALCULATOR_GUIDE_HREF,
  HOME_INSULATION_SAVINGS_CALCULATOR_LANDING_SLUG,
  HOME_INSULATION_SAVINGS_CALCULATOR_ID,
  HOME_INSULATION_SAVINGS_FOOTER_RESOURCES,
  HOME_INSULATION_SAVINGS_LANDING_SLUGS,
  HOME_INSULATION_SAVINGS_TOOL_HREF,
  HOME_INSULATION_SAVINGS_TOOL_PATH,
  getAllHomeInsulationSavingsLandings,
  getHomeInsulationSavingsLanding,
  getHomeInsulationSavingsToolFooterLinks,
  isHomeInsulationSavingsLandingSlug,
  type HomeInsulationSavingsGuideDefinition,
  type HomeInsulationSavingsLandingSlug,
} from "./homeInsulationSavingsLandings";
export {
  LED_LIGHTING_SAVINGS_AND_CO2_CALCULATOR_GUIDE_HREF,
  LED_LIGHTING_SAVINGS_AND_CO2_CALCULATOR_LANDING_SLUG,
  COMPARE_LED_VS_INCANDESCENT_BULB_COSTS_GUIDE_HREF,
  COMPARE_LED_VS_INCANDESCENT_BULB_COSTS_LANDING_SLUG,
  LED_ROI_CALCULATOR_GUIDE_HREF,
  LED_ROI_CALCULATOR_LANDING_SLUG,
  LED_SAVINGS_ROI_CALCULATOR_ID,
  LED_SAVINGS_ROI_FOOTER_RESOURCES,
  LED_SAVINGS_ROI_LANDING_SLUGS,
  LED_SAVINGS_ROI_TOOL_HREF,
  LED_SAVINGS_ROI_TOOL_PATH,
  getAllLedSavingsRoiLandings,
  getLedSavingsRoiLanding,
  getLedSavingsRoiToolFooterLinks,
  isLedSavingsRoiLandingSlug,
  type LedSavingsRoiGuideDefinition,
  type LedSavingsRoiLandingSlug,
} from "./ledSavingsRoiLandings";
export {
  ESTIMATE_MONTHLY_AND_ANNUAL_ELECTRICITY_COSTS_GUIDE_HREF,
  ESTIMATE_MONTHLY_AND_ANNUAL_ELECTRICITY_COSTS_LANDING_SLUG,
  CALCULATE_HOME_ELECTRICITY_USAGE_BY_CATEGORY_GUIDE_HREF,
  CALCULATE_HOME_ELECTRICITY_USAGE_BY_CATEGORY_LANDING_SLUG,
  WHOLE_HOUSE_ENERGY_BUDGET_CALCULATOR_GUIDE_HREF,
  WHOLE_HOUSE_ENERGY_BUDGET_CALCULATOR_LANDING_SLUG,
  WHOLE_HOUSE_ENERGY_BUDGET_CALCULATOR_ID,
  WHOLE_HOUSE_ENERGY_BUDGET_FOOTER_RESOURCES,
  WHOLE_HOUSE_ENERGY_BUDGET_LANDING_SLUGS,
  WHOLE_HOUSE_ENERGY_BUDGET_TOOL_HREF,
  WHOLE_HOUSE_ENERGY_BUDGET_TOOL_PATH,
  getAllWholeHouseEnergyBudgetLandings,
  getWholeHouseEnergyBudgetLanding,
  getWholeHouseEnergyBudgetToolFooterLinks,
  isWholeHouseEnergyBudgetLandingSlug,
  type WholeHouseEnergyBudgetGuideDefinition,
  type WholeHouseEnergyBudgetLandingSlug,
} from "./wholeHouseEnergyBudgetLandings";
export {
  HOME_EV_CHARGING_COST_ESTIMATOR_GUIDE_HREF,
  HOME_EV_CHARGING_COST_ESTIMATOR_LANDING_SLUG,
  COST_TO_CHARGE_ELECTRIC_CAR_AT_HOME_GUIDE_HREF,
  COST_TO_CHARGE_ELECTRIC_CAR_AT_HOME_LANDING_SLUG,
  EV_CHARGING_COST_CALCULATOR_GUIDE_HREF,
  EV_CHARGING_COST_CALCULATOR_LANDING_SLUG,
  EV_CHARGING_COST_CALCULATOR_ID,
  EV_CHARGING_COST_FOOTER_RESOURCES,
  EV_CHARGING_COST_LANDING_SLUGS,
  EV_CHARGING_COST_TOOL_HREF,
  EV_CHARGING_COST_TOOL_PATH,
  getAllEvChargingCostLandings,
  getEvChargingCostLanding,
  getEvChargingCostToolFooterLinks,
  isEvChargingCostLandingSlug,
  type EvChargingCostGuideDefinition,
  type EvChargingCostLandingSlug,
} from "./evChargingCostLandings";
export {
  CALCULATE_SOLAR_CAPACITY_FROM_DAILY_ENERGY_USAGE_GUIDE_HREF,
  CALCULATE_SOLAR_CAPACITY_FROM_DAILY_ENERGY_USAGE_LANDING_SLUG,
  ESTIMATE_SOLAR_PANEL_WATTAGE_NEEDED_GUIDE_HREF,
  ESTIMATE_SOLAR_PANEL_WATTAGE_NEEDED_LANDING_SLUG,
  SOLAR_PANEL_SIZE_CALCULATOR_GUIDE_HREF,
  SOLAR_PANEL_SIZE_CALCULATOR_LANDING_SLUG,
  SOLAR_PANEL_SIZE_CALCULATOR_ID,
  SOLAR_PANEL_SIZE_FOOTER_RESOURCES,
  SOLAR_PANEL_SIZE_LANDING_SLUGS,
  SOLAR_PANEL_SIZE_TOOL_HREF,
  SOLAR_PANEL_SIZE_TOOL_PATH,
  getAllSolarPanelSizeLandings,
  getSolarPanelSizeLanding,
  getSolarPanelSizeToolFooterLinks,
  isSolarPanelSizeLandingSlug,
  type SolarPanelSizeGuideDefinition,
  type SolarPanelSizeLandingSlug,
} from "./solarPanelSizeLandings";
export {
  WATTS_TO_AMPS_CALCULATOR_GUIDE_HREF,
  WATTS_TO_AMPS_CALCULATOR_LANDING_SLUG,
  CALCULATE_AMPS_FROM_WATTS_AND_VOLTAGE_GUIDE_HREF,
  CALCULATE_AMPS_FROM_WATTS_AND_VOLTAGE_LANDING_SLUG,
  CONVERT_WATTS_TO_AMPS_FOR_ELECTRICAL_LOAD_GUIDE_HREF,
  CONVERT_WATTS_TO_AMPS_FOR_ELECTRICAL_LOAD_LANDING_SLUG,
  WATTS_TO_AMPS_CALCULATOR_ID,
  WATTS_TO_AMPS_FOOTER_RESOURCES,
  WATTS_TO_AMPS_LANDING_SLUGS,
  WATTS_TO_AMPS_TOOL_HREF,
  WATTS_TO_AMPS_TOOL_PATH,
  getAllWattsToAmpsLandings,
  getWattsToAmpsLanding,
  getWattsToAmpsToolFooterLinks,
  isWattsToAmpsLandingSlug,
  type WattsToAmpsGuideDefinition,
  type WattsToAmpsLandingSlug,
} from "./wattsToAmpsLandings";
export {
  getCalculatorHref,
  getCalculatorIdFromToolPath,
} from "../calculator-routes";
export {
  CALCULATOR_USE_CASES,
  getCalculatorUseCase,
  getCalculatorsForUseCase,
  getSortedUseCaseCalculatorIds,
  getUseCaseById,
  isCalculatorUseCase,
  type CalculatorUseCase,
  type CalculatorUseCaseId,
} from "../calculator-use-cases";

import { getAllCalculatorMeta as _getAllCalculatorMeta } from "./registry";

/** @deprecated Use `getAllCalculatorMeta()` */
export const CALCULATOR_LIST = _getAllCalculatorMeta();

/** @deprecated Use `getCalculatorMeta` */
export { getCalculatorMeta as getCalculator } from "./registry";
