import { writeFileSync } from "fs";
import { join } from "path";
import { calculators } from "../src/data/calculators";
import {
  CALCULATOR_CATEGORY_LABELS,
  type CalculatorCategory,
} from "../src/data/calculator-types";

const OUTPUT = join(process.cwd(), "CALCULATORS.md");
const SITE_URL = "https://wattquick.com";

const CATEGORY_ORDER = Object.keys(
  CALCULATOR_CATEGORY_LABELS
) as CalculatorCategory[];

type CalculatorEntry = (typeof calculators)[number];

function groupByCategory() {
  const groups = new Map<CalculatorCategory, CalculatorEntry[]>();
  for (const category of CATEGORY_ORDER) {
    groups.set(category, []);
  }
  for (const calc of calculators) {
    groups.get(calc.category)!.push(calc);
  }
  return groups;
}

function formatSummaryTable(perCategory: Map<CalculatorCategory, number>) {
  const rows = CATEGORY_ORDER.map((category) => {
    const label = CALCULATOR_CATEGORY_LABELS[category];
    const count = perCategory.get(category) ?? 0;
    return `| ${label} | ${count} |`;
  });
  return [
    "| Category | Calculators |",
    "| --- | ---: |",
    ...rows,
    `| **Total** | **${calculators.length}** |`,
  ].join("\n");
}

function generateMarkdown(): string {
  const groups = groupByCategory();
  const perCategory = new Map<CalculatorCategory, number>();
  for (const [category, items] of groups) {
    perCategory.set(category, items.length);
  }

  const generatedAt = new Date().toISOString().replace("T", " ").slice(0, 16);

  const lines: string[] = [
    "# WattQuick Calculator Inventory",
    "",
    "> **Auto-generated** from [`src/data/calculators.ts`](src/data/calculators.ts).",
    "> Do not edit this file by hand — run `npm run generate:calculators` after changing calculators.",
    "",
    `Generated: ${generatedAt} UTC`,
    "",
    "## Summary",
    "",
    `- **Total calculators:** ${calculators.length}`,
    ...CATEGORY_ORDER.map((category) => {
      const count = perCategory.get(category) ?? 0;
      return `- **${CALCULATOR_CATEGORY_LABELS[category]}:** ${count}`;
    }),
    "",
    formatSummaryTable(perCategory),
    "",
    "---",
    "",
    "## Calculators by category",
    "",
  ];

  for (const category of CATEGORY_ORDER) {
    const items = groups.get(category) ?? [];
    const label = CALCULATOR_CATEGORY_LABELS[category];
    lines.push(`### ${label} (${items.length})`, "");

    if (items.length === 0) {
      lines.push("_No calculators in this category yet._", "");
      continue;
    }

    for (const calc of items) {
      const url = `${SITE_URL}${calc.href}/`;
      lines.push(
        `#### ${calc.title}`,
        "",
        `- **Slug:** \`${calc.slug}\``,
        `- **URL:** ${url}`,
        `- **Category:** ${label}`,
        `- **Description:** ${calc.description}`,
        ""
      );
    }
  }

  lines.push("---", "", "## Quick slug list", "", "```");
  for (const calc of calculators) {
    lines.push(calc.slug);
  }
  lines.push("```", "");

  return lines.join("\n");
}

const markdown = generateMarkdown();
writeFileSync(OUTPUT, markdown, "utf8");
console.log(`Wrote ${OUTPUT} (${calculators.length} calculators)`);
